version: '3'

services:
  postgres:
    container_name: car_rental_postgres
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: car_rental
      POSTGRES_PASSWORD: car_rental
      POSTGRES_DB: car_rental
    volumes:
       - ~/storage/car_rental/postgres:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - car_rental
    restart: always

  postgres_test:
    container_name: car_rental_postgres_test
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: car_rental
      POSTGRES_PASSWORD: car_rental
      POSTGRES_DB: car_rental_test
    volumes:
       - ~/storage/car_rental/postgres:/data/postgres
    ports:
      - "5437:5432"
    networks:
      - car_rental
    restart: always

networks:
  car_rental:
    driver: bridge